# This is the basic CI workflow
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Linting Workflow
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm -g i npm@next-7
      - run: npm ci
      - run: npm run ci:lint
  # Testing Workflow
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/*/node_modules
            !packages/*/node_modules/@material
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package-lock.json') }}
      - name: Install node modules
        run: npm install
      - name: bootstrap
        run: npm run bootstrap
      - name: Run test suite
        run: npm run test
